<!-- 
RSS generated by JIRA (6.4.11#64026-sha1:78f6ec473a3f058bd5d6c30e9319c7ab376bdb9c) at Fri Dec 23 10:14:21 UTC 2016

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://jira.spring.io/si/jira.issueviews:issue-xml/SEC-2367/SEC-2367.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>Spring JIRA</title>
    <link>https://jira.spring.io</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>6.4.11</version>
        <build-number>64026</build-number>
        <build-date>25-08-2015</build-date>
    </build-info>

<item>
            <title>[SEC-2367] ProviderManager doesn&apos;t report InternalAuthenticationServiceExceptions</title>
                <link>https://jira.spring.io/browse/SEC-2367</link>
                <project id="10040" key="SEC">Spring Security</project>
                    <description>&lt;p&gt;If the &lt;tt&gt;ProviderManager&lt;/tt&gt; has multiple &lt;tt&gt;AuthenticationProviders&lt;/tt&gt; and one of the earlier providers throws an &lt;tt&gt;InternalAuthenticationServiceException&lt;/tt&gt; then it will not be reported if a later provider throws any kind of &lt;tt&gt;AuthenticationException&lt;/tt&gt;.&lt;/p&gt;

&lt;p&gt;I experienced this when the errors that were occurring from a misconfigured LDAP provider were masked by the &lt;tt&gt;UsernameNotFoundException&lt;/tt&gt; from the subsequent dao provider.&lt;/p&gt;

&lt;p&gt;Given the javadocs for &lt;tt&gt;InternalAuthenticationServiceException&lt;/tt&gt; it sounds like these errors should be logged even if a subsequent authentication provider succeeds (or fails).  Perhaps &lt;tt&gt;ProviderManager.authenticate()&lt;/tt&gt; should have a special case for handling IASEs like it does for {{AccountStatusException}}s.&lt;/p&gt;</description>
                <environment></environment>
        <key id="51377">SEC-2367</key>
            <summary>ProviderManager doesn&apos;t report InternalAuthenticationServiceExceptions</summary>
                <type id="1" iconUrl="https://jira.spring.io/images/icons/issuetypes/bug.png">Bug</type>
                                            <priority id="3" iconUrl="https://jira.spring.io/images/icons/priorities/major.png">Major</priority>
                        <status id="6" iconUrl="https://jira.spring.io/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are not closed can be reopened.">Closed</status>
                    <statusCategory id="3" key="done" colorName="green"/>
                                    <resolution id="1">Fixed</resolution>
                                        <assignee username="rwinch">Rob Winch</assignee>
                                    <reporter username="jgibson">John Gibson</reporter>
                        <labels>
                    </labels>
                <created>Thu, 17 Oct 2013 09:50:04 +0000</created>
                <updated>Sat, 6 Feb 2016 06:23:12 +0000</updated>
                            <resolved>Wed, 4 Dec 2013 14:19:52 +0000</resolved>
                                    <version>3.2.0.RC1</version>
                                    <fixVersion>3.2.0</fixVersion>
                                    <component>Core</component>
                        <due></due>
                            <votes>0</votes>
                                    <watches>4</watches>
                                                                <comments>
                            <comment id="96119" author="rwinch" created="Wed, 4 Dec 2013 14:20:49 +0000"  >&lt;p&gt;ProviderManager now rethrows InternalAuthenticationServiceExceptions&lt;/p&gt;</comment>
                            <comment id="105055" author="zyro" created="Sun, 29 Jun 2014 04:12:08 +0000"  >&lt;p&gt;i think the fix (i.e. re-throwing the exception) causes totally undesired behavior requiring a manual work-around e.g. in the following situation:&lt;/p&gt;
&lt;ul&gt;
	&lt;li&gt;two authentication providers (ldap and db)&lt;/li&gt;
	&lt;li&gt;ldap is not reachable (java.net.UnknownHostException --&amp;gt; javax.naming.CommunicationException --&amp;gt; org.springframework.security.authentication.InternalAuthenticationServiceException)&lt;/li&gt;
&lt;/ul&gt;


&lt;p&gt;before this change, the db authentication was attempted when ldap was down. now, no further authentication providers are polled when one throws a InternalAuthenticationServiceException.&lt;/p&gt;

&lt;p&gt;looks like this is intentional when the exception is rethrown (see the AccountStatusException case).&lt;br/&gt;
the OPs primary concern was logging - perhaps the ProviderManager should just log instead of rethrow the exception?&lt;/p&gt;

&lt;p&gt;my dirty current workaround is to catch the InternalAuthenticationServiceException in my LdapAuthenticationProvider and rethrow a AuthenticationServiceException...&lt;/p&gt;

&lt;p&gt;thanks, zyro&lt;/p&gt;</comment>
                            <comment id="108251" author="zyro" created="Mon, 29 Sep 2014 11:55:06 +0000"  >&lt;p&gt;maybe this is slipping through cause its already closed... @rwinch: im a bit reluctant to raise a new one for the described behavior. a bit of feedback would be much appreciated. if a fresh issue helps tracking this, im happy to open it.&lt;/p&gt;</comment>
                            <comment id="109894" author="zyro" created="Thu, 20 Nov 2014 22:08:45 +0000"  >&lt;p&gt;one more bump here given it looks like 4.0 is closing in &lt;img class=&quot;emoticon&quot; src=&quot;https://jira.spring.io/images/icons/emoticons/smile.png&quot; height=&quot;16&quot; width=&quot;16&quot; align=&quot;absmiddle&quot; alt=&quot;&quot; border=&quot;0&quot;/&gt; --&amp;gt; should i open up a new jira for the described issue?&lt;br/&gt;
thanks, zyro&lt;/p&gt;</comment>
                            <comment id="109906" author="rwinch" created="Fri, 21 Nov 2014 06:38:14 +0000"  >&lt;p&gt;Can you outline why you want to ignore the fact that the host is not found? This sounds like a configuration error or networking error that should be alerted to the operations team.&lt;/p&gt;</comment>
                            <comment id="110032" author="zyro" created="Tue, 25 Nov 2014 11:55:15 +0000"  >&lt;p&gt;i am currently facing a sceanrio where a web-app has some users authenticating against ldap and some users authenticating against the app db. if the ldap server is (temporarily) not available, that should not impact those users authenticating against the db.&lt;/p&gt;</comment>
                            <comment id="110034" author="rwinch" created="Tue, 25 Nov 2014 12:01:56 +0000"  >&lt;p&gt;The problem with silently ignoring an error like this is it makes the LDAP server&apos;s temporary state of being down to something much longer. It also masks a configuration error (i.e. if the wrong LDAP URL were used) which is not desirable.&lt;/p&gt;

&lt;p&gt;If you need to totally ignore the error you can wrap the AuthenticationProvider in an implementation that ignores the exception, but this is not something that should really be in the framework.&lt;/p&gt;</comment>
                            <comment id="110035" author="zyro" created="Tue, 25 Nov 2014 12:08:38 +0000"  >&lt;p&gt;in fact thats exactly what we are currently doing. will stick to it. thanks again for the lightning-fast feedback &lt;img class=&quot;emoticon&quot; src=&quot;https://jira.spring.io/images/icons/emoticons/smile.png&quot; height=&quot;16&quot; width=&quot;16&quot; align=&quot;absmiddle&quot; alt=&quot;&quot; border=&quot;0&quot;/&gt;&lt;/p&gt;</comment>
                            <comment id="125366" author="issuemaster" created="Sat, 6 Feb 2016 06:23:12 +0000"  >&lt;p&gt;This issue has been migrated to &lt;a href=&quot;https://github.com/spring-projects/spring-security/issues/2589&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://github.com/spring-projects/spring-security/issues/2589&lt;/a&gt;&lt;/p&gt;</comment>
                    </comments>
                    <attachments>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                                            <customfield id="customfield_10170" key="com.atlassian.jira.ext.charting:firstresponsedate">
                        <customfieldname>First Response Date</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>Wed, 4 Dec 2013 14:20:49 +0000</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_10280" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Global Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>37865</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_10880" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>0|i06n7j:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_10380" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>38798</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_10381" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Ranking</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>37567</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                    <customfield id="customfield_10171" key="com.atlassian.jira.ext.charting:timeinstatus">
                        <customfieldname>Time in Status</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                </customfields>
    </item>
</channel>
</rss>